import type { CodexPmTask } from "../types/task.js";
import type { DocIndexEntry } from "../types/state.js";
import { ensureDirectoryExists } from "./file-utils.js";
import * as fs from "fs";
import * as path from "path";

export interface PromptContext {
  task: CodexPmTask;
  docs: DocIndexEntry[];
  memory?: string[];
}

export interface PromptBuilderOptions {
  baseDir?: string;
  promptsDir?: string;
}

export class PromptBuilder {
  private promptsDir: string;

  constructor(options: PromptBuilderOptions = {}) {
    const baseDir = options.baseDir || ".codex-pm";
    this.promptsDir = options.promptsDir || path.join(baseDir, "prompts");
  }

  buildPrompt(context: PromptContext): string {
    const { task, docs } = context;

    const lines: string[] = [];

    lines.push(`# Task: ${task.id}`);
    lines.push("");
    lines.push(`## ${task.title}`);
    lines.push("");
    lines.push(`**Priority:** ${task.priority} | **Risk:** ${task.risk} | **Size:** ${task.size}`);
    lines.push("");

    if (task.description) {
      lines.push("## Description");
      lines.push(task.description);
      lines.push("");
    }

    if (task.depends_on.length > 0) {
      lines.push("## Dependencies");
      for (const dep of task.depends_on) {
        lines.push(`- ${dep}`);
      }
      lines.push("");
    }

    if (docs.length > 0) {
      lines.push("## Relevant Documentation");
      for (const doc of docs) {
        lines.push(`- [${doc.filename}](${doc.path})`);
      }
      lines.push("");
    }

    if (task.files_hint.length > 0) {
      lines.push("## Files to Modify");
      for (const file of task.files_hint) {
        lines.push(`- ${file}`);
      }
      lines.push("");
    }

    if (task.acceptance.length > 0) {
      lines.push("## Acceptance Criteria");
      for (const criteria of task.acceptance) {
        lines.push(`- [ ] ${criteria}`);
      }
      lines.push("");
    }

    if (task.verify.length > 0) {
      lines.push("## Verification Commands");
      lines.push("Run the following commands to verify the task is complete:");
      lines.push("");
      for (const cmd of task.verify) {
        lines.push("```bash");
        lines.push(cmd);
        lines.push("```");
        lines.push("");
      }
    }

    if (task.blocked_rules.length > 0) {
      lines.push("## Blocked Actions");
      lines.push("The following actions are **not allowed** for this task:");
      lines.push("");
      for (const rule of task.blocked_rules) {
        lines.push(`- ⚠️ ${rule}`);
      }
      lines.push("");
    }

    lines.push("---");
    lines.push("*Generated by Codex PM*");

    return lines.join("\n");
  }

  savePrompt(taskId: string, prompt: string): string {
    ensureDirectoryExists(this.promptsDir);
    const promptPath = path.join(this.promptsDir, `${taskId}.md`);
    fs.writeFileSync(promptPath, prompt, "utf-8");
    return promptPath;
  }

  loadPrompt(taskId: string): string | null {
    const promptPath = path.join(this.promptsDir, `${taskId}.md`);
    if (fs.existsSync(promptPath)) {
      return fs.readFileSync(promptPath, "utf-8");
    }
    return null;
  }
}
